### ISSUE TITLE
'wordrpress-hash-node' is not in the npm registry.

### ISSUE THREAD

**Issue by nil1511** [AlexAlbala/wordpress-hash-node#2]
While installing npm install wordrpress-hash-node --save
I got this error

pm ERR! argv "/home/alien/.nvm/versions/node/v0.12.0/bin/node" "/home/alien/.nvm/versions/node/v0.12.0/bin/npm" "install" "wordrpress-hash-node" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code E404

npm ERR! 404 Not Found: wordrpress-hash-node
npm ERR! 404 
npm ERR! 404 'wordrpress-hash-node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'openfuel'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:

May be it is because you have not tag your commit. Try to tag commit so that it is shown here 
https://github.com/AlexAlbala/wordpress-hash-node/releases

**Comment by AlexAlbala** [comment]
Hi,

The module is available in npm:

https://www.npmjs.com/package/wordpress-hash-node

I am using it daily and it is working fine.

Are you installing it directly? or is a dependency of other npm package?

Thank you

On 7 March 2015 at 07:31, Nilesh Suthar notifications@github.com wrote:

> While installing npm install wordrpress-hash-node --save
> I got this error
> 
> pm ERR! argv "/home/alien/.nvm/versions/node/v0.12.0/bin/node"
> "/home/alien/.nvm/versions/node/v0.12.0/bin/npm" "install"
> "wordrpress-hash-node" "--save"
> npm ERR! node v0.12.0
> npm ERR! npm v2.5.1
> npm ERR! code E404
> 
> npm ERR! 404 Not Found: wordrpress-hash-node
> npm ERR! 404
> npm ERR! 404 'wordrpress-hash-node' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name
> yourself!)
> npm ERR! 404 It was specified as a dependency of 'openfuel'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! Please include the following file with any support request:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AlexAlbala/wordpress-hash-node/issues/2.

## 

Alex Albalá

**Comment by nil1511** [comment]
I tried installing normally without any dependency. I showed the same error. As of now I have installed from git using the following cmd
`npm install AlexAlbala/wordpress-hash-node`

**Comment by patrickkunka** [comment]
I think there's a typo in the docs - it should be `npm install wordpress-hash-node` and not `npm install wordrpress-hash-node`. (there's an extra "r" between "word" and "press").

NPM install worked fine for me with the correct spelling.

**Comment by AlexAlbala** [comment]
Awesome ! haha I didn't be able to found what was happening...

Sorry I will change it :)

Thank you

**Comment by patrickkunka** [comment]
Cool - thanks for the awesome plugin, you just made a huge Wordpress to node.js user migration possible!
